controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController 

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


velocity_controller:
  ros__parameters:
    joints:
      - RR_wheel_joint
      - RL_wheel_joint

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    in_chained_mode: false
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    base_frame_id: 'base_footprint'
    rear_wheels_names: ['ack_fr_joint','ack_fl_joint']
    front_wheels_names: ['steering_joint_fr','steering_joint_fl']
    wheelbase: 1.55
    front_wheel_track: 1.2
    rear_wheel_track: 1.2
    front_wheels_radius: 0.25
    rear_wheels_radius: 0.25


