ackermann_steering_controller:
  type: ackermann_steering_controller/AckermannSteeringController

  left_steering: front_left_steering_joint
  right_steering: front_right_steering_joint
  left_wheel: rear_left_wheel_joint
  right_wheel: rear_right_wheel_joint

  wheelbase: 0.8
  track: 0.5
  front_wheels_radius: 0.1
  rear_wheels_radius: 0.1

  open_loop: false

  # ניתן להפעיל publishing לטובת debug
  publish_rate: 50.0
  use_stamped_vel: true
